services:
  sc_migrate_db:
    image: postgres:15-alpine
    container_name: sc_migrate_db
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres} -h 127.0.0.1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sc_migrate_net

volumes:
  db-data:

networks:
  sc_migrate_net:
